server:
  port: 2005

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
            - id: DICTIONARY-AGGREGATE-ID
              uri: lb://DICTIONARY-AGGREGATE
              order: 8000
              predicates:
              - Path=/api/DICTIONARY-AGGREGATE/**
              filters:
              - StripPrefix=2
#            - id: server-hi
#              uri: lb://server-hi
#              order: 8001
#              predicates:
#              - Path=/api/server2/**
#              filters:
#              - StripPrefix=2

